#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Sep 05, 2020 09:04:12 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 850x650+293+27
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "PSP CarCare"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 674 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 835 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #004040 \
        -highlightcolor black -text {Vehicle #} 
    vTcl:copy_lock $site_3_0.lab47
    text $site_3_0.tex48 \
        -background white -font {-family {Segoe UI} -size 13} \
        -foreground black -height 39 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 270 -wrap word 
    $site_3_0.tex48 configure -font "-family {Segoe UI} -size 13"
    $site_3_0.tex48 insert end text
    vTcl:DefineAlias "$site_3_0.tex48" "txtvehicleno" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter vehicle Number}
    }
    vTcl:copy_lock $site_3_0.tex48
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #004040 \
        -highlightcolor black -text {Mobile #} 
    vTcl:copy_lock $site_3_0.lab49
    text $site_3_0.tex51 \
        -background white -font {-family {Segoe UI} -size 13} \
        -foreground black -height 41 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 283 -wrap word 
    $site_3_0.tex51 configure -font "-family {Segoe UI} -size 13"
    $site_3_0.tex51 insert end text
    vTcl:DefineAlias "$site_3_0.tex51" "txtmobileno" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter mobile Number}
    }
    vTcl:copy_lock $site_3_0.tex51
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Find 
    vTcl:DefineAlias "$site_3_0.but52" "btnfind" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Click to find vehicle info}
    }
    vTcl:copy_lock $site_3_0.but52
    frame $site_3_0.fra58 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 46 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 806 
    vTcl:DefineAlias "$site_3_0.fra58" "findvehicle" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra58
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_0.tBu60 \
        -takefocus {} -text {Modify Bill} 
    vTcl:DefineAlias "$site_4_0.tBu60" "btnmodifybill" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #004040 \
        -highlightcolor black -text {Bill #} 
    vTcl:DefineAlias "$site_4_0.lab62" "lblbillno" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #004040 \
        -highlightcolor black -text {Bill Number} 
    vTcl:DefineAlias "$site_4_0.lab63" "txtbillno" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tBu60 \
        -in $site_4_0 -x 0 -relx 0.24 -y 0 -rely 0.2 -width 166 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 0 -relx 0.459 -y 0 -rely 0.2 -width 0 \
        -relwidth 0.098 -height 0 -relheight 0.38 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab63 \
        -in $site_4_0 -x 0 -relx 0.583 -y 0 -rely 0.2 -width 0 \
        -relwidth 0.334 -height 0 -relheight 0.46 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra58
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu59 \
        -takefocus {} -text {New Bill} 
    vTcl:DefineAlias "$site_3_0.tBu59" "btnnewbill" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra64 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 127 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 806 
    vTcl:DefineAlias "$site_3_0.fra64" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra64
    label $site_4_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Customer Name} 
    vTcl:DefineAlias "$site_4_0.lab66" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.lab66
    text $site_4_0.tex67 \
        -background white -font {-family {Segoe UI} -size 10} \
        -foreground black -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 414 -wrap word 
    $site_4_0.tex67 configure -font "-family {Segoe UI} -size 10"
    $site_4_0.tex67 insert end text
    vTcl:DefineAlias "$site_4_0.tex67" "txtcustomerno" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.tex67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter customer name}
    }
    vTcl:copy_lock $site_4_0.tex67
    label $site_4_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Address 
    vTcl:DefineAlias "$site_4_0.lab69" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.lab69
    text $site_4_0.tex70 \
        -background white -font {-family {Segoe UI} -size 10} \
        -foreground black -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 414 -wrap word 
    $site_4_0.tex70 configure -font "-family {Segoe UI} -size 10"
    $site_4_0.tex70 insert end text
    vTcl:DefineAlias "$site_4_0.tex70" "txtaddress" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.tex70 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter customer address}
    }
    vTcl:copy_lock $site_4_0.tex70
    label $site_4_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Vehicle Info} 
    vTcl:DefineAlias "$site_4_0.lab71" "Label1_7" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.lab71
    text $site_4_0.tex72 \
        -background white -font {-family {Segoe UI} -size 10} \
        -foreground black -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 414 -wrap word 
    $site_4_0.tex72 configure -font "-family {Segoe UI} -size 10"
    $site_4_0.tex72 insert end text
    vTcl:DefineAlias "$site_4_0.tex72" "txtvehicleinfo" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.tex72 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Vehicle Information}
    }
    vTcl:copy_lock $site_4_0.tex72
    place $site_4_0.lab66 \
        -in $site_4_0 -x 0 -relx 0.012 -y 0 -rely 0.068 -width 0 \
        -relwidth 0.128 -height 0 -relheight 0.143 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tex67 \
        -in $site_4_0 -x 0 -relx 0.149 -y 0 -rely 0.068 -width 0 \
        -relwidth 0.514 -height 0 -relheight 0.163 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab69 \
        -in $site_4_0 -x 0 -relx 0.012 -y 0 -rely 0.272 -width 0 \
        -relwidth 0.128 -height 0 -relheight 0.143 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tex70 \
        -in $site_4_0 -x 0 -relx 0.149 -y 0 -rely 0.259 -width 0 \
        -relwidth 0.514 -height 0 -relheight 0.319 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab71 \
        -in $site_4_0 -x 0 -relx 0.012 -y 0 -rely 0.529 -width 0 \
        -relwidth 0.128 -height 0 -relheight 0.141 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tex72 \
        -in $site_4_0 -x 0 -relx 0.149 -y 0 -rely 0.598 -width 0 \
        -relwidth 0.514 -height 0 -relheight 0.231 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $site_3_0.fra64
    label $site_3_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text SlNo 
    vTcl:DefineAlias "$site_3_0.lab76" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Item Name} 
    vTcl:DefineAlias "$site_3_0.lab78" "Label2_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab79 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text UOM 
    vTcl:DefineAlias "$site_3_0.lab79" "Label2_10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab80 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Qty 
    vTcl:DefineAlias "$site_3_0.lab80" "Label2_11" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Price 
    vTcl:DefineAlias "$site_3_0.lab81" "Label2_12" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab82 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Total 
    vTcl:DefineAlias "$site_3_0.lab82" "Label2_13" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo83 \
        -font TkTextFont -textvariable varcboitemname -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo83" "cboitemname" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tCo83 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select / Enter  item}
    }
    vTcl:copy_lock $site_3_0.tCo83
    text $site_3_0.tex86 \
        -background white -font TkTextFont -foreground black -height 23 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 -wrap word 
    $site_3_0.tex86 configure -font "TkTextFont"
    $site_3_0.tex86 insert end text
    vTcl:DefineAlias "$site_3_0.tex86" "txtqty" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex86 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter item Quantity}
    }
    vTcl:copy_lock $site_3_0.tex86
    text $site_3_0.tex87 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 57 -wrap word 
    $site_3_0.tex87 configure -font "TkTextFont"
    $site_3_0.tex87 insert end text
    vTcl:DefineAlias "$site_3_0.tex87" "txtprice" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tex87 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Price}
    }
    vTcl:copy_lock $site_3_0.tex87
    text $site_3_0.tex88 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 61 -wrap word 
    $site_3_0.tex88 configure -font "TkTextFont"
    $site_3_0.tex88 insert end text
    vTcl:DefineAlias "$site_3_0.tex88" "txttotal" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.tex88
    ttk::combobox $site_3_0.tCo89 \
        -font TkTextFont -textvariable varcbouom -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo89" "cbouom" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tCo89 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select UOM}
    }
    vTcl:copy_lock $site_3_0.tCo89
    button $site_3_0.but90 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$site_3_0.but90" "btnadditem" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but90 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Add Item}
    }
    vTcl:copy_lock $site_3_0.but90
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr96 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_3_0.scr96" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

    .top45.fra46.scr96.01 configure -columns Col1 \
        -height 4
        .top45.fra46.scr96.01 configure -columns {Col1}
        .top45.fra46.scr96.01 heading #0 -text {Tree}
        .top45.fra46.scr96.01 heading #0 -anchor center
        .top45.fra46.scr96.01 column #0 -width 405
        .top45.fra46.scr96.01 column #0 -minwidth 20
        .top45.fra46.scr96.01 column #0 -stretch 1
        .top45.fra46.scr96.01 column #0 -anchor w
        .top45.fra46.scr96.01 heading Col1 -text {Col1}
        .top45.fra46.scr96.01 heading Col1 -anchor center
        .top45.fra46.scr96.01 column Col1 -width 406
        .top45.fra46.scr96.01 column Col1 -minwidth 20
        .top45.fra46.scr96.01 column Col1 -stretch 1
        .top45.fra46.scr96.01 column Col1 -anchor w
    label $site_3_0.lab97 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text SlNo 
    vTcl:DefineAlias "$site_3_0.lab97" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab98 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text SlNo 
    vTcl:DefineAlias "$site_3_0.lab98" "lblitemslno" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex99 \
        -background #c0c0c0 -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #c0c0c0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state disabled -width 66 -wrap word 
    $site_3_0.tex99 configure -font "TkTextFont"
    $site_3_0.tex99 insert end text
    vTcl:DefineAlias "$site_3_0.tex99" "txtitemno" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.tex99
    label $site_3_0.lab100 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text ItemNo 
    vTcl:DefineAlias "$site_3_0.lab100" "Label5" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra102 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 56 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 835 
    vTcl:DefineAlias "$site_3_0.fra102" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra102
    button $site_4_0.but103 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Save Invoice} 
    vTcl:DefineAlias "$site_4_0.but103" "btnsave" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but104 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Print Invoice} 
    vTcl:DefineAlias "$site_4_0.but104" "btnprint" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but103 \
        -in $site_4_0 -x 0 -relx 0.024 -y 0 -rely 0.179 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but104 \
        -in $site_4_0 -x 0 -relx 0.802 -y 0 -rely 0.179 -width 107 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but106 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$site_3_0.but106" "btnclear" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but106 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Clear}
    }
    vTcl:copy_lock $site_3_0.but106
    ttk::combobox $site_3_0.tCo47 \
        -values {Material Service} -font TkTextFont -state readonly \
        -textvariable varcboitemtype -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo47" "cboitemtype" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.tCo47
    label $site_3_0.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Type 
    vTcl:DefineAlias "$site_3_0.lab48" "lblType" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text DEL 
    vTcl:DefineAlias "$site_3_0.but49" "btndelete" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Delete Item}
    }
    vTcl:copy_lock $site_3_0.but49
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.012 -y 0 -rely 0.016 -width 0 \
        -relwidth 0.097 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex48 \
        -in $site_3_0 -x 0 -relx 0.12 -y 0 -rely 0.013 -width 0 \
        -relwidth 0.352 -height 0 -relheight 0.063 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.471 -y 0 -rely 0.016 -width 0 \
        -relwidth 0.098 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex51 \
        -in $site_3_0 -x 0 -relx 0.571 -y 0 -rely 0.016 -width 0 \
        -relwidth 0.351 -height 0 -relheight 0.066 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.931 -y 0 -rely 0.016 -width 47 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra58 \
        -in $site_3_0 -x 0 -y 0 -rely 0.096 -width 0 -relwidth 1 -height 0 \
        -relheight 0.074 -anchor nw -bordermode ignore 
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 0 -relx 0.025 -y 0 -rely 0.112 -width 166 \
        -relwidth 0 -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra64 \
        -in $site_3_0 -x 0 -y 0 -rely 0.163 -width 0 -relwidth 1 -height 0 \
        -relheight 0.173 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 0 -relx -0.048 -y 0 -rely 0.341 -width 0 \
        -relwidth 0.044 -height 0 -relheight 0.031 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 261 -y 230 -width 149 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 469 -y 230 -width 56 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 537 -y 230 -width 56 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 608 -y 230 -width 56 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 672 -y 230 -width 56 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo83 \
        -in $site_3_0 -x 211 -y 264 -width 258 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex86 \
        -in $site_3_0 -x 546 -y 263 -width 56 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex87 \
        -in $site_3_0 -x 608 -y 262 -width 57 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex88 \
        -in $site_3_0 -x 672 -y 262 -width 61 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo89 \
        -in $site_3_0 -x 471 -y 264 -width 66 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but90 \
        -in $site_3_0 -x 739 -y 259 -width 27 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr96 \
        -in $site_3_0 -x 0 -y 0 -rely 0.43 -width 0 -relwidth 0.994 -height 0 \
        -relheight 0.426 -anchor nw -bordermode ignore 
    place $site_3_0.lab97 \
        -in $site_3_0 -x 4 -y 230 -width 31 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab98 \
        -in $site_3_0 -x 2 -y 263 -width 35 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex99 \
        -in $site_3_0 -x 38 -y 265 -width 66 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab100 \
        -in $site_3_0 -x 40 -y 230 -width 54 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra102 \
        -in $site_3_0 -x 0 -y 0 -rely 0.861 -width 0 -relwidth 1 -height 0 \
        -relheight 0.083 -anchor nw -bordermode ignore 
    place $site_3_0.but106 \
        -in $site_3_0 -x 767 -y 259 -width 27 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo47 \
        -in $site_3_0 -x 110 -y 264 -width 93 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 117 -y 231 -width 74 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 795 -y 258 -width 27 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra46
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 10 -y 10 -width 835 -relwidth 0 -height 674 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

